services:
    form.type.translatable_text:  
        class: translation\pxTranslationBundle\Form\Type\translatableType
        arguments: ['@service_container']
        tags:
            - { name: form.type, alias: translatable_text }
    form.type.flag_text: 
        class: translation\pxTranslationBundle\Form\Type\FlagTextType
        arguments: []
        tags:
            - { name: form.type, alias: flag_text }
    form.type.flag_textarea: 
        class: translation\pxTranslationBundle\Form\Type\FlagTextAreaType
        arguments: []
        tags:
            - { name: form.type, alias: flag_textarea }
